const INCREMENT_COUNTER = "INCREMENT_COUNTER"
const DECREMENT_COUNTER = "DECREMENT_COUNTER"
const CLEAR_COUNTER = "CLEAR_COUNTER"
export {
    DECREMENT_COUNTER,
    INCREMENT_COUNTER,
    CLEAR_COUNTER
}